# Generated by Django 5.2.3 on 2025-06-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="branch_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="school",
            name="branch_address",
        ),
        migrations.CreateModel(
            name="SchoolBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
        ),
    ]
