# Generated by Django 5.2.3 on 2025-07-14 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="isdeleted",
        ),
        migrations.RemoveField(
            model_name="schoolbranch",
            name="isdeleted",
        ),
        migrations.AddField(
            model_name="school",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": 1},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolbranch",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": 2},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schoolbranch",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_branch",
                to="schools.school",
            ),
        ),
    ]
