# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_rename_branch_name_school_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolbranch",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
    ]
