# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_principal_branch_branchmanager_schoolowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchmanager",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="principal",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolowner",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
    ]
