# Generated by Django 5.2.3 on 2025-07-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customusermodel_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customusermodel",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="is_active",
        ),
    ]
