# Generated by Django 5.2.3 on 2025-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customusermodel_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
