# Generated by Django 5.2.3 on 2025-07-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customusermodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Main Admin"),
                    ("owner", "School Owner"),
                    ("manager", "Branch Manager"),
                ],
                max_length=25,
            ),
        ),
    ]
